# Generated by Django 2.2.16 on 2020-10-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0035_auto_20201019_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='queue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Queue', verbose_name='Queue'),
        ),
    ]
