# Generated by Django 2.2.16 on 2020-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0034_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='queue',
            field=models.CharField(blank=True, max_length=30, verbose_name='Queue'),
        ),
    ]
